In [215]:
write("Selection Operators.jl",In[IJulia.n])

function roulette_wheel(p)
    threshold=rand()*sum(p)
    distrib=cumsum(p)
    return findfirst(threshold.<=distrib)
end

function rank_selection(n)
    # The population is supposed sorted: last=highest fitness
    # n size of population
    p=convert(Array,1:n)
    @show p
    i,j=roulette_wheel.([p, p])
    return i,j
end

function fitness_proportionate_selection(fitnesses)
   i,j=roulette_wheel.([fitnesses,fitnesses]) 
    return i,j
end

function selection_operator(fitnesses,proba)
    # fitnesses are sorted: lowest to highest
    operator=roulette_wheel(proba)
    if operator==1
       i,j=rank_selection(length(fitnesses)) 
    else
        i,j=fitness_proportionate_selection(fitnesses)
    end
    return i,j
end

selection_operator (generic function with 1 method)

In [213]:
write("Crossover Operators.jl",In[IJulia.n])

include("Selection Operators.jl")

function horizontal_split(parent1,parent2)
    split_at=rand(2:size(parent1,1))
    offspring1=copy(parent1)
    offspring2=copy(parent2)
    offspring1[1:split_at-1,:]=parent2[1:split_at-1,:]
    offspring2[1:split_at-1,:]=parent1[1:split_at-1,:]
    return offspring1,offspring2
end

function vertical_split(parent1,parent2)
    split_at=rand(2:size(parent1,1))
    offspring1=copy(parent1)
    offspring2=copy(parent2)
    offspring1[:,1:split_at-1]=parent2[:,1:split_at-1]
    offspring2[:,1:split_at-1]=parent1[:,1:split_at-1]
    return offspring1,offspring2    
end

function uniform_crossover(parent1,parent2)
    λ=rand()
    offspring1=λ*parent1+(1-λ)*parent2
    offspring2=λ*parent2+(1-λ)*parent1
    return offspring1,offspring2    
end

crossover_operators=[uniform_crossover, vertical_split, horizontal_split]

function crossover_operator(parent1,parent2,rate,proba)
    if rand()<rate
        i=roulette_wheel(proba)
        parent1,parent2=crossover_operators[i](parent1,parent2)
    end
    return parent1,parent2
end

crossover_operator (generic function with 1 method)

In [214]:
write("Mutation Operators.jl",In[IJulia.n])

function gaussian_perturbation(individual,rate)
    n=size(individual,1)
    pertu=randn(n,n).*(rand(n,n).<rate)
    tmp=individual+pertu
    return tmp.*(tmp.>=0)
end

function mutation_operator(individual,rate)
    return gaussian_perturbation(individual,rate)
end

mutation_operator (generic function with 1 method)

In [163]:
a=ones(4,4)

4×4 Array{Float64,2}:
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

In [195]:
gaussian_perturbation(a,1)

4×4 Array{Float64,2}:
 -0.0         1.00729   2.6788    -0.0
 -0.0         0.304917  1.61215    1.46331
  0.249676    1.5166    2.23884   -0.0
  0.0183441  -0.0       0.832279   2.33863

In [207]:
a=[]

Any[]

In [208]:
push!(a,1,2)

2-element Array{Any,1}:
 1
 2